  sql.data:
    image: microsoft/mssql-server-linux
    container_name: spaceShooterSQLServer
    environment:
      - SA_PASSWORD=HalloAffe@123
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "1433:1433"